[package]
name = "substrate-validator-set"
version = "0.2.0"
authors = ["gautamdhameja"]
edition = "2018"

[features]
default = ['std']
std = [
    'codec/std',
    'sp-std/std',
    'sp-runtime/std',
    'frame-support/std',
    'sp-core/std',
    'sp-io/std',
    'system/std',
    'serde',
    'session/std'
]

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.3.1'

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'
version = '2.0.0-rc4'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'
version = '2.0.0-rc4'

[dependencies.sp-io]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'
version = '2.0.0-rc4'

[dependencies.serde]
features = ['derive']
optional = true
version = '1.0.101'

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'
version = '2.0.0-rc4'

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'
version = '2.0.0-rc4'

[dependencies.system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'
version = '2.0.0-rc4'

[dependencies.session]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-session'
rev = '00768a1f21a579c478fe5d4f51e1fa71f7db9fd4'
version = '2.0.0-rc4'
